config/routes.rb
Quora::Application.routes.draw do
  get "activities/index"
  get "careers", to: 'footers#careers', as: 'careers'
  get "about_quora_clone", to: 'footers#about_quora_clone', as: 'about_quora_clone'
  get "notifications", to: "notifications#index", as: "notifications"

  get "inbox", to: "conversations#index", as: "inbox"
  resources :conversations, :only => [:create, :show]
  resources :messages, :only => [:create]

  resource :feed do
    get 'most_recent'
    get 'top_questions'
  end

  devise_for :users
	resources :users

	resources :questions do
		collection do
			get 'unanswered'
		end
	end

	resources :comments
  resources :topics

  resource :follow_question_relationships, :only => [:create, :destroy]
  resource :follow_user_relationships, :only => [:create, :destroy]
  resource :follow_topic_relationships, :only => [:create, :destroy]
  resource :question_topic_relationships, :only => [:create, :destroy]

  resources :topics do
    member do
      get 'trending'
    end
  end

  resources :searches, :only => [:index]

	resource :votes, :only => [:create, :destroy]

  root :to => "feeds#most_recent"
end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
  attr_accessible :is_read
  alias_attribute :is_read?, :is_read

  has_many :messages

  def mark_as_read
    self.update_attributes!(is_read: true)
  end

  def mark_as_unread
    self.update_attributes!(is_read: false)
  end

  def last_message
    self.messages.sort_by { |message| message.created_at }.last
  end

  def sender
    self.messages.first.sender
  end

  def receiver
    self.messages.first.receiver
  end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  def index
    @conversations = current_user.conversations
  end

  def show
    @conversation = Conversation
      .includes(messages: [:sender, :receiver]).find(params[:id])
    @conversation.messages.sort_by { |message| message.created_at }.reverse!
    @message = Message.new
    @conversation.mark_as_read if @conversation.last_message.sender != current_user
  end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/index.html.erb
<h3 class="inbox">Inbox</h3>
<button class="new_message_btn popup_msg_form btn btn-success">Compose New Message</button>
<br /><br /><br /><br /><br />


<table>
  <thead>
    <tr>
      <th class="span2"></th>
      <th class="span2"></th>
      <th class="span2"></th>
    </tr>
	</thead>
  <tbody>
  	<% @conversations.each do |conversation| %>
			<% user = (current_user == conversation.sender) ? conversation.receiver : conversation.sender %>
    	<tr>
      	<td><strong>With: <%= link_to user.username, user_url(user) %></strong></td>
      	<td><strong><%= link_to conversation.last_message.content, conversation_url(conversation) %></strong></td>
      	<td>
					<strong>
						<%= time_ago_in_words(conversation.last_message.created_at) %> ago
						<% if !conversation.is_read? && conversation.last_message.sender != current_user %>
							<span class="label label-important">New!</span>
						<% end %>
					</strong>
				</td>
    	</tr>
  	<% end %>
	</tbody>
</table>


<div class="new_msg_form well">
	<%= form_for Message.new do |f| %>
		<%= f.hidden_field :sender_id, :value => current_user.id %>
		<input type="text" class="receiver" name="message[receiver_name]" placeholder="Type the person's username"><br />

		<%= f.text_area :content,
			rows: 4,
			:placeholder => "Type Your Message Here",
			:class => "msg_content" %><br />

		<%= f.submit "Send Message!", :class => "btn btn-success" %>
	<% end %>

<script>
	msgFormPopup();
	msgFormAutocomplete();
</script>

app/views/conversations/show.html.erb
<h3>Conversation Between
	<%= current_user.username %>
	And
	<% counterpart = @conversation.sender == current_user ? @conversation.receiver : @conversation.sender %>
	<%= counterpart.username %>

</h3>

<div class="convo_box">
	<% @conversation.messages.each do |message| %>
		<div><strong><%= message.sender.username %></strong>:
			<%= message.content%> --<%= time_ago_in_words(message.created_at) %> ago
		</div>
			<hr width="50%">
	<% end %>
</div>

<%= form_for @message, html: { class: "new_message" }, remote: true do |f| %>
	<%= f.hidden_field :sender_id, value: current_user.id %>
	<%= f.hidden_field :receiver_id, value: counterpart.id %>
	<%= f.hidden_field :conversation_id, value: @conversation.id %>
	<%= f.text_area :content, rows: 4, class: "msg_box" %><br />
	<%= f.submit "Send", class: "btn btn-success" %>
<% end %>

<script type="text/javascript">
	var pusher = new Pusher("<%= Pusher.key %>");
	var channel = pusher.subscribe('test_channel');

	channel.bind("form_submit", function(data) {
		var name = null;
		if (parseInt("<%= current_user.id %>") === data.sender_id){
			name = "<%= current_user.username %>"
		} else {
			name = "<%= counterpart.username %>"
		}
		var template = JST["messages/show"]({
			message: data,
			sender_name: name
		})
		$(".convo_box").append(template);
		$(".convo_box").scrollTop($(".convo_box")[0].scrollHeight);

		$(".msg_box").val("");
	});
</script>