config/routes.rb
Quora::Application.routes.draw do
  get "activities/index"
  get "careers", to: 'footers#careers', as: 'careers'
  get "about_quora_clone", to: 'footers#about_quora_clone', as: 'about_quora_clone'
  get "notifications", to: "notifications#index", as: "notifications"

  get "inbox", to: "conversations#index", as: "inbox"
  resources :conversations, :only => [:create, :show]
  resources :messages, :only => [:create]

  resource :feed do
    get 'most_recent'
    get 'top_questions'
  end

  devise_for :users
	resources :users

	resources :questions do
		collection do
			get 'unanswered'
		end
	end

	resources :comments
  resources :topics

  resource :follow_question_relationships, :only => [:create, :destroy]
  resource :follow_user_relationships, :only => [:create, :destroy]
  resource :follow_topic_relationships, :only => [:create, :destroy]
  resource :question_topic_relationships, :only => [:create, :destroy]

  resources :topics do
    member do
      get 'trending'
    end
  end

  resources :searches, :only => [:index]

	resource :votes, :only => [:create, :destroy]

  root :to => "feeds#most_recent"
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  include PublicActivity::Common
  include PgSearch
  multisearchable :against => [:name]

  attr_accessible :name

  validates_uniqueness_of :name

	has_many :follow_topic_relationships

	has_many :followers,
		 			 :through => :follow_topic_relationships,
 					 :source => :follower

  has_many :question_topic_relationships, :dependent => :destroy

  has_many :questions, :through => :question_topic_relationships

  def self.trending_topics
    Topic.all.sort_by! { |topic| - topic.followers.count }
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def new
    @topic = Topic.new
  end

  def create
    @topic = Topic.new(params[:topic])
    @topic.save!
    FollowTopicRelationship.create!({topic_id: @topic.id, follower_id: current_user.id })
    @topic.create_activity :create,
      owner: current_user,
      recipient: @topic
    redirect_to topic_url(@topic)
  end

  def index
    @topics = Topic.where("name ILIKE ?", "%#{params[:q]}%")

    respond_to do |format|
      format.html
      format.json { render :json => @topics }
    end
  end

  def show
    @topic = Topic.find(params[:id])
    @question = Question.new
    @rel = FollowTopicRelationship.new
  end

  def trending
    @topic = Topic.find(params[:id])
    @questions =
      @topic
        .questions
          .sort_by { |question| question.created_at }
          .reverse!

    @question = Question.new
    @rel = FollowTopicRelationship.new
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_follow_unfollow.html.erb
<div class="followers"><%= pluralize(topic.followers.count, "Follower") %></div>

<%= form_for rel,
	:remote => true,
	:html => { :class => current_user.followed_topics.include?(topic) ? "follow_topic hidden" : "follow_topic"} do |f| %>
	<%= f.hidden_field :topic_id, :value => topic.id %>
	<button type="submit" class="btn btn-success">Follow Topic<i class="icon-ok"></i></button>
<% end %>

<%= form_for rel,
	:remote => true,
	:html => { :class => current_user.followed_topics.include?(topic) ? "unfollow_topic" : "unfollow_topic hidden",
	:method => :delete } do |f| %>
	<%= f.hidden_field :topic_id, :value => topic.id %>
	<button type="submit" class="btn btn-success">Unfollow Topic<i class="icon-ok"></i></button>
<% end %>

app/views/topics/_question_form.html.erb
<%= link_to "Add Question", "#", :class => "add_question" %>

<%= form_for question,
	:html => { :class => "add_question_form hidden"} do |f| %>
	<input type='hidden' value="<%= topic.id %>" name="topic_id" >

	<%= f.label :title %>
	<%= f.text_field :title %><br />

	<%= f.label :body %>
	<%= f.text_area :body, :rows => 2 %><br />

	<%= f.submit "Create Question", :class => "btn btn-success" %>
<% end %>

app/views/topics/new.html.erb
<h3>Create a Topic</h3>

<%= form_for @topic do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %><br />

	<button type="submit" class="btn btn-success">
		Create Topic
	</button>
<% end %>

app/views/topics/show.html.erb
<%= render :partial => "follow_unfollow", :locals => { rel: @rel, topic: @topic } %>


<h1><%= @topic.name %></h1>

<ul class="nav nav-pills">
  <li class="active"><%= link_to "All Questions", topic_url(@topic) %></li>
  <li><%= link_to "Trending", trending_topic_url(@topic) %></li>
</ul>

<br /><hr width="80%">

<%= render :partial => "question_form", :locals => { question: @question, topic: @topic } %>

<% unless @topic.questions.empty? %>
<h3>Questions</h3>
	<% @topic.questions.each do |question| %>
		<%= link_to question.title, question_url(question) %>
		<hr width="80%">
	<% end %>
<% end %>

<script>
	addTopicQuestion();
	followUnfollowTopics();
</script>

app/views/topics/trending.html.erb
<%= render :partial => "follow_unfollow", :locals => { rel: @rel, topic: @topic } %>

<h1><%= @topic.name %></h1>

<ul class="nav nav-pills">
  <li><%= link_to "All Questions", topic_url(@topic) %></li>
  <li class="active"><%= link_to "Trending", trending_topic_url(@topic) %></li>
</ul>

<br /><hr width="80%">

<%= render :partial => "question_form", :locals => { question: @question, topic: @topic } %>


<h3>Trending Questions</h3>
<% @questions.each do |question| %>
	<%= link_to question.title, question_url(question) %>
	<hr width="80%">
<% end %>

<script>
	addTopicQuestion();
	followUnfollowTopics();
</script>