config/routes.rb
Quora::Application.routes.draw do
  get "activities/index"
  get "careers", to: 'footers#careers', as: 'careers'
  get "about_quora_clone", to: 'footers#about_quora_clone', as: 'about_quora_clone'
  get "notifications", to: "notifications#index", as: "notifications"

  get "inbox", to: "conversations#index", as: "inbox"
  resources :conversations, :only => [:create, :show]
  resources :messages, :only => [:create]

  resource :feed do
    get 'most_recent'
    get 'top_questions'
  end

  devise_for :users
	resources :users

	resources :questions do
		collection do
			get 'unanswered'
		end
	end

	resources :comments
  resources :topics

  resource :follow_question_relationships, :only => [:create, :destroy]
  resource :follow_user_relationships, :only => [:create, :destroy]
  resource :follow_topic_relationships, :only => [:create, :destroy]
  resource :question_topic_relationships, :only => [:create, :destroy]

  resources :topics do
    member do
      get 'trending'
    end
  end

  resources :searches, :only => [:index]

	resource :votes, :only => [:create, :destroy]

  root :to => "feeds#most_recent"
end

app/views/shared/_index_sidebar.html.erb
<div id="index_sidebar">
	<hr>
	<strong><%= link_to "Ask a Question", new_question_url, :id => 'create_question' %></strong><br />
	<strong><%= link_to "Unanswered Questions", unanswered_questions_url%></strong>
	<hr>
	<h5>Trending Topics</h5>
	<% Topic.trending_topics[0..5].each do |topic| %>
		<strong><%= link_to topic.name, topic_url(topic) %></strong><br />
	<% end %>
	<hr>
	<h5>Review</h5>
	<strong><%= link_to "All Questions", questions_url %></strong>
	<hr>
	<div class="fb-like" data-href="http://dominic-wong-quora-clone.herokuapp.com/" data-send="true" data-layout="button_count" data-width="50" data-show-faces="true"></div>
	<br /><br />
	<a href="https://twitter.com/share" class="twitter-share-button" data-url="http://dominic-wong-quora-clone.herokuapp.com/" data-via="dominicwong617">
		Tweet
	</a>
	<br /><br />
	<div class="g-plus" data-action="share" data-annotation="bubble" data-href="http://dominic-wong-quora-clone.herokuapp.com/"></div>
</div>

<script>
	!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');
</script>

<!-- Google plugin -->
<script type="text/javascript">
  (function() {
    var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
    po.src = 'https://apis.google.com/js/plusone.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
  })();
</script>

<!-- Facebook plugin -->
<div id="fb-root"></div>
<script>
	(function(d, s, id) {
	  var js, fjs = d.getElementsByTagName(s)[0];
	  if (d.getElementById(id)) return;
	  js = d.createElement(s); js.id = id;
	  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=295380833941632";
	  fjs.parentNode.insertBefore(js, fjs);
	}(document, 'script', 'facebook-jssdk'));
</script>

app/views/shared/_question_loop.html.erb
<ul>
	<% questions.each do |question| %>
	 	<li data-id="<%= question.id %>">
		  <%= link_to question.title, question_url(question) %>
			<% if question.topics %>
				<% question.topics[0..2].each do |topic| %>
					<span class="label label-important">
						<%= topic.name %>
					</span>
				<% end %>
			<% end %>
		</li>
		<hr width="60%">
  <% end %>
</ul>

app/views/shared/_top_bar.html.erb
<% ["feed", "top_questions", "most_recent"].each do |page| %>
	<% page = "inactive" %>
<% end %>

<% if link == "feed" %>
	<% feed = "active" %>
<% elsif link == "top_questions" %>
	<% top_questions = "active" %>
<% else %>
	<% most_recent = "active" %>
<% end %>

<br />
<ul class="nav nav-pills">
  <li class="<%= most_recent %>"><%= link_to "Most Recent", most_recent_feed_url %></li>
	<li class="<%= feed %>"><%= link_to "Feed", activities_index_url %></li>
  <li class="<%= top_questions %>"><%= link_to "Most Followed", top_questions_feed_url %></li>
</ul>