config/routes.rb
Quora::Application.routes.draw do
  get "activities/index"
  get "careers", to: 'footers#careers', as: 'careers'
  get "about_quora_clone", to: 'footers#about_quora_clone', as: 'about_quora_clone'
  get "notifications", to: "notifications#index", as: "notifications"

  get "inbox", to: "conversations#index", as: "inbox"
  resources :conversations, :only => [:create, :show]
  resources :messages, :only => [:create]

  resource :feed do
    get 'most_recent'
    get 'top_questions'
  end

  devise_for :users
	resources :users

	resources :questions do
		collection do
			get 'unanswered'
		end
	end

	resources :comments
  resources :topics

  resource :follow_question_relationships, :only => [:create, :destroy]
  resource :follow_user_relationships, :only => [:create, :destroy]
  resource :follow_topic_relationships, :only => [:create, :destroy]
  resource :question_topic_relationships, :only => [:create, :destroy]

  resources :topics do
    member do
      get 'trending'
    end
  end

  resources :searches, :only => [:index]

	resource :votes, :only => [:create, :destroy]

  root :to => "feeds#most_recent"
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def index
    @results = PgSearch.multisearch(params[:query])
      .paginate(:page => params[:page], :per_page => 10)
  end
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/index.html.erb
<h1>Search Results</h1>

<% if @results.empty? %>
	<h3>Sorry! Your search did not return any results :(</h3>
<% end %>

<% @results.each do |result| %>
	<% if result.searchable_type == "Question" %>
		<% question = Question.find(result.searchable_id) %>
		<h3>Question:</h3>
		<%= link_to question.title, question_url(question), :class => "result_body" %>
		<br /><br />
	<% elsif result.searchable_type == "User" %>
		<% user = User.find(result.searchable_id) %>
		<h3>User:</h3>
		<%= link_to user.username, user_url(user), :class => "result_body" %>
		<br /><br />
	<% elsif result.searchable_type == "Topic" %>
		<% topic = Topic.find(result.searchable_id) %>
		<h3>Topic:</h3>
		<%= link_to topic.name, topic_url(topic), :class => "result_body" %>
		<br /><br />
	<% end %>
<% end %>

<%= will_paginate @results %>